apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mcp
spec:
  selector:
    app: ddt-mcp
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: {{ .Values.mcp.port }}
  type: ClusterIP
