apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-n8n
spec:
  selector:
    app: ddt-n8n
  ports:
    - port: {{ .Values.n8n.port }}
      targetPort: {{ .Values.n8n.port }}
  type: ClusterIP
