apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: ddt-postgres
    {{- include "ddt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddt-postgres
  template:
    metadata:
      labels:
        app: ddt-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.POSTGRES_DB | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.env.POSTGRES_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.env.POSTGRES_PASSWORD | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
        - name: init-scripts
          configMap:
            name: {{ .Release.Name }}-postgres-init
